In [1]:
import numpy as np

In [2]:
np.array([1, 2, 1])

array([1, 2, 1])

In [3]:
a = np.array([1.0, 2, 1])

In [4]:
a.dtype

dtype('float64')

In [5]:
np.array([1.9, 2, 1], dtype='int')
# converting float to int cuts numbers

array([1, 2, 1])

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
print(a.ndim)
print(a.shape) # 2 rows, 3 columns
print(a.size) # the total size of the array

2
(2, 3)
6


In [8]:
print(a.itemsize, "bytes") # each element
print(a.nbytes, "bytes")
a.itemsize * a.size

8 bytes
48 bytes


48

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [13]:
np.full((3, 2), 'hello there')

array([['hello there', 'hello there'],
       ['hello there', 'hello there'],
       ['hello there', 'hello there']], dtype='<U11')

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# uninitialized array
np.empty(6) # the values will be whatever happens to already exist at that memory location

array([4.6711473e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000])

In [19]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [21]:
# uniform distribution
np.random.random((3, 2))

array([[0.56387515, 0.48629152],
       [0.35527803, 0.03589338],
       [0.63377532, 0.08155511]])

In [22]:
# normal distribution
# mean = 0, sd = 1
np.random.normal(0, 1, (3, 3))

array([[ 0.25919643, -0.54533194, -0.70983446],
       [-1.69215054,  0.44143079,  0.26699262],
       [ 1.36153174,  0.98146249, -0.51735294]])

In [23]:
a = np.random.rand(4, 4)
print(a)

[[0.93285661 0.5125267  0.44907109 0.7221466 ]
 [0.23801342 0.39465657 0.31700118 0.40965993]
 [0.63567212 0.71763745 0.22555184 0.76927263]
 [0.57624998 0.03816234 0.2542776  0.66615823]]


In [25]:
b = np.random.randint(1, 10, size=(6,6))
print(b)

[[7 2 8 5 5 7]
 [5 7 5 4 9 1]
 [5 7 2 8 9 1]
 [5 2 5 8 2 4]
 [3 7 1 3 3 6]
 [7 6 6 6 9 8]]


# Accessing elements

In [26]:
print(b[0])
print(b[0,2])
print(b[0,-1])
print(b[0,1:])
print(b[0,:3]) 
print(b[0,1:5])
print('')
print(b[0,::2]) # every other element
print(b[0,1::2]) # every other element, starting at index 1
print(b[0,::-1]) # if step is negative, start and stop are swapped (a convenient way to reverse an array)
print('')
print(b[:3,:3])

[7 2 8 5 5 7]
8
7
[2 8 5 5 7]
[7 2 8]
[2 8 5 5]

[7 8 5]
[2 5 7]
[7 5 5 8 2 7]

[[7 2 8]
 [5 7 5]
 [5 7 2]]


In [27]:
# a[start:stop:step]
a = np.random.randint(1, 10, size=(6, 6))
print(a)

a[1,1:5:2]

[[6 8 4 4 5 1]
 [6 3 1 6 8 6]
 [8 3 8 9 3 5]
 [5 7 2 4 4 4]
 [7 6 3 6 5 6]
 [9 8 7 5 7 5]]


array([3, 6])

In [28]:
a[1,2] = 100
print(a)

[[  6   8   4   4   5   1]
 [  6   3 100   6   8   6]
 [  8   3   8   9   3   5]
 [  5   7   2   4   4   4]
 [  7   6   3   6   5   6]
 [  9   8   7   5   7   5]]


In [29]:
a = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]])
print(a)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


In [30]:
a[2,0,0]

100

In [31]:
a[:,:,2] = 0
print(a)

[[[  1   2   0]
  [  4   5   0]]

 [[ 10  20   0]
  [ 40  50   0]]

 [[100 200   0]
  [400 500   0]]]


In [32]:
# slices return views rather than copies of the array data
print(b)

[[7 2 8 5 5 7]
 [5 7 5 4 9 1]
 [5 7 2 8 9 1]
 [5 2 5 8 2 4]
 [3 7 1 3 3 6]
 [7 6 6 6 9 8]]


In [34]:
# extract subarray
b_sub = b[:3,:3]
print(b_sub)

[[7 2 8]
 [5 7 5]
 [5 7 2]]


In [35]:
# original array is changed
b_sub[0,0] = 100
print(b_sub)

[[100   2   8]
 [  5   7   5]
 [  5   7   2]]


In [36]:
print(b)

[[100   2   8   5   5   7]
 [  5   7   5   4   9   1]
 [  5   7   2   8   9   1]
 [  5   2   5   8   2   4]
 [  3   7   1   3   3   6]
 [  7   6   6   6   9   8]]


In [37]:
b_sub_copy = b[:3,:3].copy()
print(b_sub_copy)

[[100   2   8]
 [  5   7   5]
 [  5   7   2]]


In [38]:
b_sub_copy[0,0] = 1000

print(b_sub_copy)

[[1000    2    8]
 [   5    7    5]
 [   5    7    2]]


In [39]:
print(b_sub)

[[100   2   8]
 [  5   7   5]
 [  5   7   2]]


In [41]:
# fancy indexing
a = np.array([1, 2, 3, 4, 5, 6, 7])
indexes = [0, 4, 5]
a[indexes]

array([1, 5, 6])

In [42]:
a[indexes] = 99
print(a)

[99  2  3  4 99 99  7]


In [43]:
row_ind = np.array([0, 1, 2])
col_ind = np.array([0, 1, 2])
b_sub[row_ind, col_ind]

array([100,   7,   2])

In [44]:
# combining fancy indices with simple indices and slicing
print(b_sub[2, [0, 1]])
print('')
print(b_sub[1:, [0, 2]])

[5 7]

[[5 5]
 [5 2]]


# Reshaping, stacking, slicing

In [45]:
a = np.arange(1, 5)
print(a)

[1 2 3 4]


In [46]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [47]:
# concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [48]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9], [10, 11, 12]])

print(np.concatenate([c, d]))
print('')
print(np.concatenate([c, d], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [52]:
a = np.full((2,2), 10)
b = np.full((1,2), 2)
c = np.full((2,1), 5)
print(a)
print('')
print(b)
print('')
print(c)

[[10 10]
 [10 10]]

[[2 2]]

[[5]
 [5]]


In [53]:
# for working with arrays of mixed dimensions

print(np.vstack([a,b]))
print('')
print(np.hstack([a,c]))

[[10 10]
 [10 10]
 [ 2  2]]

[[10 10  5]
 [10 10  5]]


In [54]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x1, x2, x3 = np.split(a, [3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8]


In [56]:
# there is also hsplit and vsplit

# Math

In [57]:
a = np.array([1, 2, 3])
print(a)
b = np.array([10, 20, 30])
print(b)

[1 2 3]
[10 20 30]


In [58]:
print(-a)
print(a - 1)
print(a + b)
print(a * b) # elementwise
print(b / a)
print(a // 2) # floor division
print(a % 2) # mod
print(b ** a)

[-1 -2 -3]
[0 1 2]
[11 22 33]
[10 40 90]
[10. 10. 10.]
[0 1 1]
[1 0 1]
[   10   400 27000]


In [59]:
print(np.add.accumulate(a))
print(np.multiply.accumulate(a))

[1 3 6]
[1 2 6]


In [60]:
# NumPy allows you to work with arrays of different dimensions, as if stretching a smaller array to a larger one. 
# It's called broadcasting.
b = np.zeros((3,3))

print(a)
print('+')
print(b)
print('=')
print(a+b)

[1 2 3]
+
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
=
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [61]:
a = np.arange(1, 11)
np.multiply.outer(a, a)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [62]:
print(np.exp(a)) # e^a
print(np.log(a)) # ln(a)
print(np.log2(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


In [63]:
a = np.array([-1, -2, -3])
np.abs(a)

array([1, 2, 3])

In [64]:
a = np.full((3,2), 2)
print(a)
b = np.full((2,3), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]
[[2 2 2]
 [2 2 2]]


In [65]:
np.matmul(a, b)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [66]:
a = np.random.randint(-9, 10, (5, 5))
print(a)

[[ 1 -7  7 -8  7]
 [-6  4  4  6  2]
 [-6 -1  1  7 -2]
 [ 0  8 -7 -4  7]
 [-2  6  8 -4 -2]]


In [57]:
np.sin(a) # trigonometry
# there are also inverse and hyperbolic trigonometric functions, see documentation

array([[ 0.6569866 , -0.2794155 , -0.90929743,  0.7568025 , -0.84147098],
       [ 0.90929743, -0.6569866 , -0.6569866 ,  0.7568025 ,  0.2794155 ],
       [ 0.6569866 , -0.41211849,  0.90929743, -0.98935825,  0.7568025 ],
       [ 0.90929743,  0.6569866 , -0.7568025 ,  0.6569866 , -0.14112001],
       [ 0.95892427, -0.84147098,  0.90929743, -0.95892427, -0.7568025 ]])

# Boolean arrays, masking

In [67]:
# comparison operators: >, >=, <, <=, !=, ==
print(a >= 0)

[[ True False  True False  True]
 [False  True  True  True  True]
 [False False  True  True False]
 [ True  True False False  True]
 [False  True  True False False]]


In [68]:
# boolean masking
print(a[a >= 0])

[1 7 7 4 4 6 2 1 7 0 8 7 6 8]


In [69]:
# elementwise comparison
a == a

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [70]:
print(np.any(a > 1)) # there are the elements > 1, at least one
print(np.all(a > 1)) # not all the elements > 1

# you can specify axis

True
False


In [71]:
# you can use operators such &, |, ~
b = ~((a > 0) & (a < 5))
print(b)

[[False  True  True  True  True]
 [ True False False  True False]
 [ True  True False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [72]:
print(np.sum(b))
print(np.sum(~b))

20
5


# Aggregations

In [73]:
a = np.random.randint(-99, 100, (5, 5))
print(a)

[[-80  24 -86  99 -32]
 [-23  34  82  97  38]
 [  2 -59 -38  76 -49]
 [ 95  38  15 -31   7]
 [-54 -33 -58  92 -78]]


In [74]:
print('Max:', np.max(a))
print('Min:', np.min(a))

Max: 99
Min: -86


In [75]:
a.max()

99

In [76]:
print(a.min(axis=0)) # the min within each column
print(a.min(axis=1)) # the min within each row

[-80 -59 -86 -31 -78]
[-86 -23 -59 -31 -78]


In [77]:
print(np.mean(a))
print(np.var(a)) # variance
print(np.std(a)) # standard deviation
print(np.median(a))

3.12
3637.7056
60.31339486382772
2.0


In [78]:
# computing quantiles
print("25th percentile:", np.percentile(a, 25))
print("75th percentile:", np.percentile(a, 75))

25th percentile: -49.0
75th percentile: 38.0


# Sorting

In [79]:
a = np.array([5, 2, 1, 4, 3])
np.sort(a)
# returns a copy of the array

array([1, 2, 3, 4, 5])

In [80]:
print(a)
a.sort()
print(a)
# returns the changed array

[5 2 1 4 3]
[1 2 3 4 5]


In [81]:
# return indexes
a = np.array([5, 2, 1, 4, 3])
np.argsort(a)

array([2, 1, 4, 3, 0])

In [82]:
# sort by axis
a = np.array([[5, 2, 8], [3, 5, 1]])
print(a)
np.sort(a, axis=0)

[[5 2 8]
 [3 5 1]]


array([[3, 2, 1],
       [5, 5, 8]])

In [83]:
np.sort(a, axis=1)

array([[2, 5, 8],
       [1, 3, 5]])