### Find two sentences that are closest in meaning to the first one.

In [173]:
import numpy as np
import re

a = []

f = open('sentences.txt', 'r') # extracting data
for line in f:
    line = line.lower()
    line = re.split('[^a-z]', line) # using regexp for tokenization
    
    # removing empty strings
    for word in line:
        if (word != ''):
            a.append(word)
            
a = list(set(a)) # removing duplicates

print(a)

['felis', 'it', 'redirection', 'undergone', 'arguments', 'offered', 'according', 'concatenate', 'may', 'single', 'later', 'recent', 'error', 'closest', 'installs', 'safari', 'predators', 'starting', 'legibility', 'process', 'simply', 'can', 'faint', 'are', 'installation', 'place', 'command', 'marks', 'roughly', 'features', 'purchase', 'some', 'used', 'left', 'safer', 'those', 'sounds', 'human', 'learned', 'download', 'drive', 'from', 'any', 'october', 'for', 'versions', 'won', 'genes', 'concern', 'genus', 'moved', 'store', 'cat', 'to', 'world', 'where', 'however', 'connected', 'streams', 'permanently', 'clear', 'pipes', 'receives', 'has', 'os', 'releasing', 'off', 'tiger', 'linux', 'output', 'two', 'entirely', 'in', 'stdout', 'available', 'file', 'mice', 'bytes', 'you', 'high', 'instead', 'is', 'contains', 'also', 'predecessor', 'members', 'second', 'release', 'separate', 'named', 'so', 'stdin', 'mac', 'yosemite', 'now', 'or', 'count', 'changes', 'selection', 'firmware', 'will', 'their

In [151]:
dict = {}
d = len(a)

for i in range(d): # dict indexing
    dict[i] = a[i]
print(dict)

{0: 'felis', 1: 'it', 2: 'redirection', 3: 'undergone', 4: 'arguments', 5: 'offered', 6: 'according', 7: 'concatenate', 8: 'may', 9: 'single', 10: 'later', 11: 'recent', 12: 'error', 13: 'closest', 14: 'installs', 15: 'safari', 16: 'predators', 17: 'starting', 18: 'legibility', 19: 'process', 20: 'simply', 21: 'can', 22: 'faint', 23: 'are', 24: 'installation', 25: 'place', 26: 'command', 27: 'marks', 28: 'roughly', 29: 'features', 30: 'purchase', 31: 'some', 32: 'used', 33: 'left', 34: 'safer', 35: 'those', 36: 'sounds', 37: 'human', 38: 'learned', 39: 'download', 40: 'drive', 41: 'from', 42: 'any', 43: 'october', 44: 'for', 45: 'versions', 46: 'won', 47: 'genes', 48: 'concern', 49: 'genus', 50: 'moved', 51: 'store', 52: 'cat', 53: 'to', 54: 'world', 55: 'where', 56: 'however', 57: 'connected', 58: 'streams', 59: 'permanently', 60: 'clear', 61: 'pipes', 62: 'receives', 63: 'has', 64: 'os', 65: 'releasing', 66: 'off', 67: 'tiger', 68: 'linux', 69: 'output', 70: 'two', 71: 'entirely', 72

In [152]:
# creating the matrix of occurrences

matrix = np.zeros((22, d), np.int) 
matrix.shape

(22, 254)

In [174]:
f = open('sentences.txt', 'r')
row = 0

for line in f:
    line = line.lower()
    line = re.split('[^a-z]', line)
    for key,value in dict.items():
        if value in line:
            matrix[[row],[key]] += 1
            
#            print(value)
#    print(line)
#    print('(line ', row + 1, ')', sep='')
#    print('----------------')

    row += 1

In [154]:
print(matrix)
print(matrix[0])

print(matrix[[0],[52]])  # line 1 doesn't contain the 'cat'
print(matrix[[0],[133]]) # but it does contain the 'cats'

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0]
[1]


In [172]:
from scipy.spatial import distance

for k in range(1, 22):
    print('Distance to ', k + 1, ': ', distance.cosine(matrix[0],matrix[k]), sep='')
    # cosine distance from sentence 1 to sentence k

Distance to 2: 0.9402385695332803
Distance to 3: 0.8619868881315291
Distance to 4: 0.8885443574849294
Distance to 5: 0.8055388829343507
Distance to 6: 0.9351796276447836
Distance to 7: 0.7547442642060137
Distance to 8: 0.9154845745271484
Distance to 9: 0.9069515789601529
Distance to 10: 0.8833576312960392
Distance to 11: 0.8703592552895671
Distance to 12: 0.8703592552895671
Distance to 13: 0.8773721321030068
Distance to 14: 0.8703592552895671
Distance to 15: 0.8619868881315291
Distance to 16: 0.9402385695332803
Distance to 17: 0.85361498905772
Distance to 18: 0.9503708333014534
Distance to 19: 0.9442721787424647
Distance to 20: 0.9402385695332803
Distance to 21: 0.8427572744917122
Distance to 22: 0.8250364469440588


# 7 and 5 is the answer.